# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCAlertView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'LCCAlertController'
# pod 'LCCAlertController', :path => '../..'

  # Pods for LCAlertView

  target 'LCAlertViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LCAlertViewUITests' do
    # Pods for testing
  end

end
